env:
  - CGO_ENABLED=0
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
    - go mod download
builds:
- env:
  goos:
    - darwin
    - windows
    - linux
  goarch:
    - amd64
    - arm
    - arm64
  ignore:
    - goos: darwin
      goarch: arm
    - goos: windows
      goarch: arm
    - goos: windows
      goarch: arm64
  mod_timestamp: '{{ .CommitTimestamp }}'
  binary: asap-tools-cli
  flags:
    - -trimpath
  main: ./cmd/asap-tools-cli/main.go
  ldflags: >
    -s
    -X github.com/gebv/asap-tools/version.Version={{.Version}}
    -X github.com/gebv/asap-tools/version.GitCommit={{.Commit}}
    -X github.com/gebv/asap-tools/version.BuildDate={{.Date}}
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
snapshot:
  name_template: '{{.Version}}-SNAPSHOT-{{.ShortCommit}}'
release:
  footer: |
    **Full Changelog**: https://github.com/gebv/asap-tools/compare/{{ .PreviousTag }}...{{ .Tag }}
  github:
      owner: gebv
      name: asap-tools
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format: zip
    files:
      - README.md
      - LICENSE
      # TODO: add example config

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^chore:"
      - "^chore\\(deps\\):"
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch
      - '^MERGE'
      - "{{ .Tag }}"
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999

brews:
  - name: asap-tools
    folder: Formula
    tap:
      owner: gebv
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage:  https://github.com/gebv/asap-tools
    description: The asap-tools it is collection of tools to simplify daily monotonous monotonous cases. For syncing tasks between ClickUp teams and more.
    license: MIT
    test: |
      system "#{bin}/asap-tools-cli -v"
    install: |
      bin.install "asap-tools"
