name: Snapshot

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Get previous tag
      run:
        echo "PREVIOUS_TAG=$(git -c log.showSignature=false describe --abbrev=0 ${GITHUB_REF#refs/*/}^)" >> $GITHUB_ENV

    - name: Install goreleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        install-only: true

    - name: Release
      run: make release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
        GORELEASER_PREVIOUS_TAG: ${{ env.PREVIOUS_TAG }}
